"""Initial migration

Revision ID: eaaddf3a2a96
Revises: 
Create Date: 2023-09-18 19:10:47.432691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaaddf3a2a96'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cupcakes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flavor', sa.String(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cupcakes')
    # ### end Alembic commands ###
